server:
  class: src.server.Server
  client_manager:
    class: src.server.client_managers.SimpleClientManager
  strategy:
    class: src.server.strategies.FedAvg
    args:
      min_fit_clients: 10 # clients_per_round
      log: False
    valuation: null
app:
  client:
    class: src.apps.clients.ClassificationClient
    args: 
      local_epochs : 1
      batch_size : 32
      fedprox_mu: 0.01
wandb_args:
  group: 'cifar10_fedprox' 
