server:
  class: src.server.Server
  client_manager:
    class: src.server.client_managers.SimpleClientManager
  strategy:
    class: src.server.strategies.FedAvg
    args:
      min_fit_clients: 10 # clients_per_round
      log: False
    valuation: null
wandb_args:
  group: 'cifar10_fedavg' 
